In [ ]:
# Question 1. Pandas version

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.3.1'

In [46]:
# Question 2. Records count
# How many records are in the dataset?

In [71]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [57]:
df.shape

(9704, 11)

In [48]:
# Question 3. Fuel types
# How many fuel types are presented in the dataset?

In [24]:
pd.read_csv('car_fuel_efficiency.csv')

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [56]:
df['fuel_type'].nunique()

2

In [50]:
# Question 4. Missing values
# How many columns in the dataset have missing values?

In [55]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [59]:
# Question 5. Max fuel efficiency
# What's the maximum fuel efficiency of cars from Asia?

In [13]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [8]:
# Question 6. Median value of horsepower
'''
Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?
'''

'\nFind the median value of the horsepower column in the dataset.\nNext, calculate the most frequent value of the same horsepower column.\nUse the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.\nNow, calculate the median value of horsepower once again.\nHas it changed?\n'

In [ ]:
#1 Find the median value of the horsepower column in the dataset.

In [158]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [159]:
original_median = df['horsepower'].median()
print(f"Original median horsepower: {original_median}")


Original median horsepower: 149.0


In [28]:
#2 calculate the most frequent value of the same horsepower column.

In [160]:
most_frequent_hp = df['horsepower'].mode()[0]
print(f"Most frequent horsepower value: {most_frequent_hp}")

Most frequent horsepower value: 152.0


In [38]:
#3 Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [161]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

In [46]:
# calculate the median value of horsepower once again.

In [162]:
new_median = df['horsepower'].median()
print(f"New median horsepower after filling missing values: {new_median}")

New median horsepower after filling missing values: 152.0


In [77]:
# Question 7. Sum of weights 
'''
Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.
'''


"\nSelect all the cars from Asia\nSelect only columns vehicle_weight and model_year\nSelect the first 7 values\nGet the underlying NumPy array. Let's call it X.\nCompute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.\nInvert XTX.\nCreate an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].\nMultiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.\nWhat's the sum of all the elements of the result?\nNote: You just implemented linear regression. We'll talk about it in the next lesson.\n"

In [88]:
#1 Select all the cars from Asia
cars_from_Asia = df[df['origin']=='Asia']

In [90]:
#2 Select only columns vehicle_weight and model_year
cars_from_Asia[['vehicle_weight','model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [93]:
#3 Select the first 7 values
cars_from_Asia[['vehicle_weight','model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [99]:
#4 Get the underlying NumPy array. Let's call it X.
X = cars_from_Asia[['vehicle_weight','model_year']].head(7).to_numpy()

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [100]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [ ]:
#5 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [102]:
import numpy as np

In [145]:
XTX = np.dot(X.T, X)

In [144]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [104]:
#6 Invert XTX.

In [147]:
XTX_inv = np.linalg.inv(XTX)

In [148]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [108]:
#7 Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [149]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [111]:
#8 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [150]:
XTX_inv.shape, X.T.shape

((2, 2), (2, 7))

In [152]:
z = np.dot(XTX_inv, X.T)

In [124]:
z.shape, y.shape

((2, 7), (7,))

In [153]:
w = np.dot(z, y)

In [154]:
w

array([0.01386421, 0.5049067 ])

In [121]:
#9 What's the sum of all the elements of the result?

In [155]:
w.sum()


np.float64(0.5187709081074016)